app:
  telegram-token: ${TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  config: classpath:log4j2-plain.xml
