/*
 * This file is generated by jOOQ.
 */
package edu.java.dao.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Question implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private Integer answerCount;
    private Integer commentCount;

    public Question() {}

    public Question(Question value) {
        this.linkId = value.linkId;
        this.answerCount = value.answerCount;
        this.commentCount = value.commentCount;
    }

    @ConstructorProperties({ "linkId", "answerCount", "commentCount" })
    public Question(
        @NotNull Long linkId,
        @Nullable Integer answerCount,
        @Nullable Integer commentCount
    ) {
        this.linkId = linkId;
        this.answerCount = answerCount;
        this.commentCount = commentCount;
    }

    /**
     * Getter for <code>QUESTION.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>QUESTION.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>QUESTION.ANSWER_COUNT</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return this.answerCount;
    }

    /**
     * Setter for <code>QUESTION.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Integer answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * Getter for <code>QUESTION.COMMENT_COUNT</code>.
     */
    @Nullable
    public Integer getCommentCount() {
        return this.commentCount;
    }

    /**
     * Setter for <code>QUESTION.COMMENT_COUNT</code>.
     */
    public void setCommentCount(@Nullable Integer commentCount) {
        this.commentCount = commentCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Question other = (Question) obj;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.answerCount == null) {
            if (other.answerCount != null)
                return false;
        }
        else if (!this.answerCount.equals(other.answerCount))
            return false;
        if (this.commentCount == null) {
            if (other.commentCount != null)
                return false;
        }
        else if (!this.commentCount.equals(other.commentCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.answerCount == null) ? 0 : this.answerCount.hashCode());
        result = prime * result + ((this.commentCount == null) ? 0 : this.commentCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Question (");

        sb.append(linkId);
        sb.append(", ").append(answerCount);
        sb.append(", ").append(commentCount);

        sb.append(")");
        return sb.toString();
    }
}
