/*
 * This file is generated by jOOQ.
 */
package edu.java.dao.jooq.tables.records;


import edu.java.dao.jooq.tables.Question;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestionRecord extends UpdatableRecordImpl<QuestionRecord> implements Record3<Long, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>QUESTION.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>QUESTION.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>QUESTION.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>QUESTION.ANSWER_COUNT</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>QUESTION.COMMENT_COUNT</code>.
     */
    public void setCommentCount(@Nullable Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>QUESTION.COMMENT_COUNT</code>.
     */
    @Nullable
    public Integer getCommentCount() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Question.QUESTION.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return Question.QUESTION.ANSWER_COUNT;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return Question.QUESTION.COMMENT_COUNT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer component2() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Integer component3() {
        return getCommentCount();
    }

    @Override
    @NotNull
    public Long value1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer value2() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Integer value3() {
        return getCommentCount();
    }

    @Override
    @NotNull
    public QuestionRecord value1(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public QuestionRecord value2(@Nullable Integer value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public QuestionRecord value3(@Nullable Integer value) {
        setCommentCount(value);
        return this;
    }

    @Override
    @NotNull
    public QuestionRecord values(@NotNull Long value1, @Nullable Integer value2, @Nullable Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestionRecord
     */
    public QuestionRecord() {
        super(Question.QUESTION);
    }

    /**
     * Create a detached, initialised QuestionRecord
     */
    @ConstructorProperties({ "linkId", "answerCount", "commentCount" })
    public QuestionRecord(@NotNull Long linkId, @Nullable Integer answerCount, @Nullable Integer commentCount) {
        super(Question.QUESTION);

        setLinkId(linkId);
        setAnswerCount(answerCount);
        setCommentCount(commentCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised QuestionRecord
     */
    public QuestionRecord(edu.java.dao.jooq.tables.pojos.Question value) {
        super(Question.QUESTION);

        if (value != null) {
            setLinkId(value.getLinkId());
            setAnswerCount(value.getAnswerCount());
            setCommentCount(value.getCommentCount());
            resetChangedOnNotNull();
        }
    }
}
